## 4.2 벡터의 내적과 놈

In [1]:
import numpy as np 
a = np.array([1, 2, 3])
b = np.array([3, 2, 1])

print("--- dot() 함수 ---")
print(np.dot(a, b))
print("--- 곱의 총합 ---")
print(sum(a * b)

--- dot() 함수 ---
10
--- 곱의 총합 ---
10


In [2]:
#놈의 구현
a = np.array([1, 1, -1, -1])

print("--- L2놈 ---")
print(np.linalg.norm(a))
print("--- L1놈 ---")
print(np.linalg.norm(a, 1))

--- L2놈 ---
2.0
--- L1놈 ---
4.0


In [9]:
import numpy as np

a = np.array([1, -2, 2])
b = np.array([2, -2, 1])

print("--- 내적 ---")
print(np.dot(a, b))
print(np.sum(a*b))
print("--- L1놈 ---")
print(np.linalg.norm(a, 1))
print(np.linalg.norm(b, 1))
print("--- L2놈 ---")
print(np.linalg.norm(a))
print(np.linalg.norm(b))

--- 내적 ---
8
8
--- L1놈 ---
5.0
5.0
--- L2놈 ---
3.0
3.0


In [15]:
# ------- 솔로런 -------

word_list = ["home", "happy", "happiness", "hello", "apple"]

input_letter = input()

for word in word_list:
    if input_letter in word:
        print(word)


a
happy
happiness
apple


In [17]:
import numpy as np 

a = np.array([[0, 1, 2], 
             [1, 2, 3]])

b = np.array([[2, 1],
             [2, 1],
             [2, 1]])

print(np.dot(a, b))

[[ 6  3]
 [12  6]]


In [20]:
import numpy as np

a = np.array([[0, 1, 2],
             [3, 4, 5],
             [6, 7, 8]])

b = np.array([[0, 1, 2],
            [2, 0, 1],
            [1, 2, 0]])

print(a*b)

[[ 0  1  4]
 [ 6  0  5]
 [ 6 14  0]]


In [21]:
import numpy as np

a = np.array([[0, 1, 2],
             [1, 2, 3]])

b = np.array([[0, 1],
             [1, 2],
             [2, 3]])

print(np.dot(a, b))

c = np.array([[0, 1, 2],
            [3, 4, 5],
            [6, 7, 8]])
d = np.array([[0, 2, 0],
             [2, 0, 2],
             [0, 2, 0]])

print(c*d)


[[ 5  8]
 [ 8 14]]
[[ 0  2  0]
 [ 6  0 10]
 [ 0 14  0]]
