## 4.4 전치

In [1]:
import numpy as np

a = np.array([[1, 2, 3],
            [4, 5, 6]])
print(a.T)

[[1 4]
 [2 5]
 [3 6]]


In [2]:
import numpy as np

a = np.array([[0, 1, 2],
             [1, 2, 3]])
b = np.array([[0, 1, 2], 
             [1, 2, 3]])

#print(np.dot(a,b)) 전치하지 않고 행렬곱을 취하면 에러 발생 
print(np.dot(a, b.T))

[[ 5  8]
 [ 8 14]]


In [4]:
import numpy as np 

a = np.array([[0, 1, 2], 
             [1, 2, 3]])
b = np.array([[0, 1, 2], 
             [2, 3, 4]])

print(np.dot(a.T, b))
print(np.dot(a, b.T))

[[ 2  3  4]
 [ 4  7 10]
 [ 6 11 16]]
[[ 5 11]
 [ 8 20]]


## 4.5 행렬식과 역행렬

In [5]:
import numpy as np

print(np.eye(2))
print()
print(np.eye(3))
print()
print(np.eye(4))

[[1. 0.]
 [0. 1.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [7]:
import numpy as np 

a = np.array([[1, 2],
             [3, 4]])
print(np.linalg.det(a))

b = np.array([[1, 2],
             [0, 0]])
print(np.linalg.det(b))

-2.0000000000000004
0.0


In [8]:
import numpy as np 

a = np.array([[1, 2],
             [3, 4]])
print(np.linalg.inv(a))

b = np.array([[1, 2]
             [0, 0]])
print(np.linalg.inv(b)) #역행렬이 존재하지 않으므로 에러가 난다 

[[-2.   1. ]
 [ 1.5 -0.5]]


<>:7: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:7: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<ipython-input-8-f000e3df39cc>:7: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  b = np.array([[1, 2]


TypeError: list indices must be integers or slices, not tuple

In [10]:
import numpy as np 

a = np.array([[1, 1], 
             [1, 2]])

print(np.linalg.det(a))

print(np.linalg.inv(a))

1.0
[[ 2. -1.]
 [-1.  1.]]
